package com.crm.sales.order.presentation.web;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import com.crm.sales.order.domain.OrderAction;
import com.crm.sales.order.domain.OrderPricingMode;
import com.crm.sales.order.domain.OrderSourceType;
import com.crm.sales.order.domain.OrderStatus;

public record OrderResponse(
		UUID id,
		String orderNumber,
		OrderSourceType sourceType,
		OrderPricingMode pricingMode,
		OrderStatus status,
		OrderReferenceResponse account,
		OrderReferenceResponse contact,
		OrderReferenceResponse opportunity,
		OrderReferenceResponse quote,
		OrderReferenceResponse priceBook,
		OrderOwnerReferenceResponse owner,
		OrderAmountsResponse amounts,
		OrderAddressSnapshotResponse billingAddressSnapshot,
		OrderAddressSnapshotResponse shippingAddressSnapshot,
		List<OrderLineResponse> lines,
		BigDecimal progressPercent,
		LocalDate orderDate,
		LocalDate requestedDeliveryDate,
		String customerReference,
		String paymentTerms,
		String deliveryTerms,
		String notes,
		Instant confirmedAt,
		String confirmedBy,
		Instant fulfilledAt,
		Instant cancelledAt,
		String cancelledBy,
		String cancellationReason,
		Instant closedAt,
		String closedBy,
		String closedReason,
		Instant createdAt,
		String createdBy,
		Instant updatedAt,
		String updatedBy,
		long version,
		List<OrderAction> availableActions
) {}
