package com.crm.marketing.campaign.domain;

public enum CampaignErrorCode {

	CAMPAIGN_NOT_FOUND("CAMPAIGN_NOT_FOUND"),
	CAMPAIGN_CODE_ALREADY_EXISTS("CAMPAIGN_CODE_ALREADY_EXISTS"),
	CAMPAIGN_MEMBER_NOT_FOUND("CAMPAIGN_MEMBER_NOT_FOUND"),
	CAMPAIGN_MEMBER_ALREADY_EXISTS("CAMPAIGN_MEMBER_ALREADY_EXISTS"),
	INVALID_CAMPAIGN_DATES("INVALID_CAMPAIGN_DATES"),
	INVALID_CAMPAIGN_MEMBER_TARGET("INVALID_CAMPAIGN_MEMBER_TARGET"),
	CAMPAIGN_VERSION_CONFLICT("CAMPAIGN_VERSION_CONFLICT"),
	LEAD_NOT_FOUND("LEAD_NOT_FOUND"),
	CONTACT_NOT_FOUND("CONTACT_NOT_FOUND");

	private final String code;

	CampaignErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return code;
	}

}
