import React from 'react';

export const Header: React.FC = () => {
  return (
    <header className="bg-surface-container-lowest text-primary flex justify-between items-center px-lg docked full-width top-0 sticky z-40 border-b border-outline-variant flat no shadows font-body-sm text-body-sm font-label-md text-label-md ml-0 shadow-sm md:ml-56 h-[48px] text-xs">
<div className="flex items-center gap-4"><span className="material-symbols-outlined text-outline cursor-pointer text-lg">apps</span><div className="font-bold text-base hidden md:block">VUM CRM</div><div className="hidden md:flex gap-3 ml-4 items-center"><button className="text-on-surface-variant font-medium hover:text-primary transition-colors flex items-center gap-1 text-xs">Dự án <span className="material-symbols-outlined text-xs">expand_more</span></button><button className="text-on-surface-variant font-medium hover:text-primary transition-colors flex items-center gap-1 text-xs">Bộ lọc <span className="material-symbols-outlined text-xs">expand_more</span></button><button className="text-on-surface-variant font-medium hover:text-primary transition-colors flex items-center gap-1 text-xs">Bảng điều khiển <span className="material-symbols-outlined text-xs">expand_more</span></button><button className="bg-primary-container text-on-primary h-[28px] px-2.5 rounded text-xs font-medium hover:bg-primary-container/90 transition flex items-center gap-1">+ Tạo mới</button></div></div>
<div className="flex items-center gap-4"><div className="relative hidden lg:block"><span className="material-symbols-outlined absolute left-2 top-1/2 -translate-y-1/2 text-outline text-xs">search</span><input className="h-[28px] pl-7 pr-2 border border-[#DFE1E6] rounded text-xs focus:border-primary-container focus:ring-2 focus:ring-primary-container/20 outline-none bg-surface-container-lowest w-40" placeholder="Search..." type="text" /></div><div className="bg-secondary-container/30 text-primary-container px-2 py-0.5 rounded text-[10px] font-bold flex items-center gap-1 cursor-pointer"><span className="material-symbols-outlined text-xs">smart_toy</span> AI</div><div className="flex items-center gap-2 text-outline"><div className="relative cursor-pointer hover:text-primary transition-colors"><span className="material-symbols-outlined text-lg">notifications</span><span className="absolute -top-0.5 -right-0.5 bg-error text-white text-[8px] w-3.5 h-3.5 flex items-center justify-center rounded-full">3</span></div><span className="material-symbols-outlined cursor-pointer hover:text-primary transition-colors hidden md:block text-lg">settings</span><span className="text-xs font-semibold cursor-pointer hover:text-primary transition-colors hidden md:block">VI</span></div><div className="w-7 h-7 rounded-full bg-secondary-container flex items-center justify-center text-primary-fixed font-bold text-xs ml-1 border border-outline-variant cursor-pointer">VP</div></div>
</header>
  );
};
