package com.crm.integration.domain;

public enum IntegrationErrorCode {

	WEBHOOK_SUBSCRIPTION_NOT_FOUND("WEBHOOK_SUBSCRIPTION_NOT_FOUND"),
	WEBHOOK_DELIVERY_NOT_FOUND("WEBHOOK_DELIVERY_NOT_FOUND"),
	EXTERNAL_MAPPING_NOT_FOUND("EXTERNAL_MAPPING_NOT_FOUND"),
	EXTERNAL_MAPPING_ALREADY_EXISTS("EXTERNAL_MAPPING_ALREADY_EXISTS"),
	INVALID_WEBHOOK_URL("INVALID_WEBHOOK_URL"),
	INVALID_EVENT_TYPES("INVALID_EVENT_TYPES"),
	INTEGRATION_VERSION_CONFLICT("INTEGRATION_VERSION_CONFLICT");

	private final String code;

	IntegrationErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return code;
	}

}
