package com.crm.sales.contract.domain;

public enum ContractErrorCode {

	CONTRACT_NOT_FOUND("CONTRACT_NOT_FOUND"),
	CONTRACT_NUMBER_ALREADY_EXISTS("CONTRACT_NUMBER_ALREADY_EXISTS"),
	INVALID_CONTRACT_STATUS_TRANSITION("INVALID_CONTRACT_STATUS_TRANSITION"),
	CONTRACT_ALREADY_SIGNED("CONTRACT_ALREADY_SIGNED"),
	CONTRACT_NOT_ACTIVE("CONTRACT_NOT_ACTIVE"),
	CONTRACT_ACCOUNT_INVALID("CONTRACT_ACCOUNT_INVALID"),
	CONTRACT_VERSION_CONFLICT("CONTRACT_VERSION_CONFLICT");

	private final String code;

	ContractErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return code;
	}

}
