package com.crm.service.category.domain;

public enum ServiceErrorCode {

	TICKET_CATEGORY_NOT_FOUND("TICKET_CATEGORY_NOT_FOUND"),
	TICKET_CATEGORY_CODE_ALREADY_EXISTS("TICKET_CATEGORY_CODE_ALREADY_EXISTS"),
	PARENT_CATEGORY_NOT_FOUND("PARENT_CATEGORY_NOT_FOUND"),
	CYCLIC_CATEGORY_HIERARCHY("CYCLIC_CATEGORY_HIERARCHY"),
	SLA_POLICY_NOT_FOUND("SLA_POLICY_NOT_FOUND"),
	TICKET_NOT_FOUND("TICKET_NOT_FOUND"),
	TICKET_NUMBER_ALREADY_EXISTS("TICKET_NUMBER_ALREADY_EXISTS"),
	TICKET_COMMENT_NOT_FOUND("TICKET_COMMENT_NOT_FOUND"),
	TICKET_ACCOUNT_REQUIRED("TICKET_ACCOUNT_REQUIRED"),
	INVALID_TICKET_STATUS_TRANSITION("INVALID_TICKET_STATUS_TRANSITION"),
	SERVICE_VERSION_CONFLICT("SERVICE_VERSION_CONFLICT");

	private final String code;

	ServiceErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return code;
	}

}
