import { AppRouteManifestItem, NavigationGroupDefinition } from '@/types/navigation';

export const NAVIGATION_GROUP_DEFINITIONS: NavigationGroupDefinition[] = [
  { id: 'crm', titleKey: 'nav.crmGroup', order: 10 },
  { id: 'sales', titleKey: 'nav.salesGroup', order: 20 },
  { id: 'catalog', titleKey: 'nav.catalogGroup', order: 30 },
  { id: 'service', titleKey: 'nav.serviceGroup', order: 40 },
  { id: 'marketing', titleKey: 'nav.marketingGroup', order: 50 },
  { id: 'privacy', titleKey: 'nav.privacyGroup', order: 60 },
  { id: 'integration', titleKey: 'nav.integrationGroup', order: 70 },
  { id: 'audit', titleKey: 'nav.auditGroup', order: 80 },
  { id: 'platform', titleKey: 'nav.platformGroup', order: 90 },
];

export const APP_ROUTE_MANIFEST: AppRouteManifestItem[] = [
  // Primary (ungrouped) items
  {
    id: 'overview',
    titleKey: 'nav.overview',
    path: '/app/overview',
    matchPatterns: ['/app/overview'],
    iconName: 'LayoutDashboard',
    access: { kind: 'authenticated' },
    showInSidebar: true,
    showInCommandPalette: true,
    order: 0,
  },
  {
    id: 'profile',
    titleKey: 'common.profile',
    path: '/app/profile',
    matchPatterns: ['/app/profile'],
    iconName: 'User',
    access: { kind: 'authenticated' },
    showInSidebar: false,
    showInCommandPalette: true,
    order: 5,
  },

  // CRM
  {
    id: 'crm-accounts',
    titleKey: 'nav.customers',
    path: '/app/crm/accounts',
    matchPatterns: ['/app/crm/accounts', '/app/crm/accounts/:id'],
    iconName: 'Building2',
    access: { kind: 'permission', code: 'crm_account.read' },
    groupId: 'crm',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'crm-contacts',
    titleKey: 'nav.contacts',
    path: '/app/crm/contacts',
    matchPatterns: ['/app/crm/contacts'],
    iconName: 'Users',
    access: { kind: 'permission', code: 'crm_contact.read' },
    groupId: 'crm',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },
  {
    id: 'crm-leads',
    titleKey: 'nav.leads',
    path: '/app/crm/leads',
    matchPatterns: ['/app/crm/leads'],
    iconName: 'UserPlus',
    access: { kind: 'permission', code: 'crm_lead.read' },
    groupId: 'crm',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 30,
  },
  {
    id: 'crm-opportunities',
    titleKey: 'nav.opportunities',
    path: '/app/crm/opportunities',
    matchPatterns: ['/app/crm/opportunities', '/app/crm/opportunities/:id'],
    iconName: 'TrendingUp',
    access: { kind: 'permission', code: 'crm_opportunity.read' },
    groupId: 'crm',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 40,
  },
  {
    id: 'crm-activities',
    titleKey: 'nav.activities',
    path: '/app/crm/activities',
    matchPatterns: ['/app/crm/activities', '/app/crm/activities/:activityId'],
    iconName: 'Calendar',
    // Previously: requiresAnyCrmReadPermission
    access: { kind: 'any-permission', codes: ['crm_account.read', 'crm_contact.read', 'crm_lead.read', 'crm_opportunity.read'] },
    groupId: 'crm',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 50,
  },

  // Sales
  {
    id: 'sales-forecast',
    titleKey: 'nav.forecast', // Wait, the vi file doesn't have nav.forecast. But that's okay, we'll keep the key for now.
    path: '/app/sales/forecast',
    matchPatterns: ['/app/sales/forecast'],
    iconName: 'BarChart3',
    access: { kind: 'permission', code: 'crm_opportunity.read' },
    groupId: 'sales',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'sales-quotes',
    titleKey: 'nav.quotes',
    path: '/app/sales/quotes',
    matchPatterns: ['/app/sales/quotes'],
    iconName: 'FileText',
    access: { kind: 'permission', code: 'sales_quote.read' },
    groupId: 'sales',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },
  {
    id: 'sales-orders',
    titleKey: 'nav.orders',
    path: '/app/sales/orders',
    matchPatterns: ['/app/sales/orders'],
    iconName: 'ShoppingCart',
    access: { kind: 'permission', code: 'sales_order.read' },
    groupId: 'sales',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 30,
  },
  {
    id: 'sales-contracts',
    titleKey: 'nav.contracts',
    path: '/app/sales/contracts',
    matchPatterns: ['/app/sales/contracts'],
    iconName: 'FileSignature',
    access: { kind: 'permission', code: 'sales_order.read' },
    groupId: 'sales',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 40,
  },

  // Catalog
  {
    id: 'catalog-categories',
    titleKey: 'nav.productCategories',
    path: '/app/catalog/categories',
    matchPatterns: ['/app/catalog/categories'],
    iconName: 'FolderTree',
    access: { kind: 'tenant-admin' },
    groupId: 'catalog',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'catalog-products',
    titleKey: 'nav.products',
    path: '/app/catalog/products',
    matchPatterns: ['/app/catalog/products'],
    iconName: 'Package',
    access: { kind: 'tenant-admin' },
    groupId: 'catalog',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },
  {
    id: 'catalog-pricebooks',
    titleKey: 'nav.priceBooks',
    path: '/app/catalog/price-books',
    matchPatterns: ['/app/catalog/price-books'],
    iconName: 'Tag',
    access: { kind: 'tenant-admin' },
    groupId: 'catalog',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 30,
  },

  // Service
  {
    id: 'service-tickets',
    titleKey: 'nav.tickets',
    path: '/app/service/tickets',
    matchPatterns: ['/app/service/tickets'],
    iconName: 'LifeBuoy',
    access: { kind: 'permission', code: 'service_ticket.read' },
    groupId: 'service',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },

  // Marketing
  {
    id: 'marketing-campaigns',
    titleKey: 'nav.campaigns',
    path: '/app/marketing/campaigns',
    matchPatterns: ['/app/marketing/campaigns'],
    iconName: 'Megaphone',
    access: { kind: 'tenant-admin' },
    groupId: 'marketing',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },

  // Privacy
  {
    id: 'privacy-consent',
    titleKey: 'nav.privacyConsent',
    path: '/app/privacy/consent',
    matchPatterns: ['/app/privacy/consent'],
    iconName: 'ShieldCheck',
    access: { kind: 'permission', code: 'privacy_consent.read' },
    groupId: 'privacy',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'privacy-retention',
    titleKey: 'nav.retentionPolicy',
    path: '/app/privacy/retention',
    matchPatterns: ['/app/privacy/retention'],
    iconName: 'Archive',
    access: { kind: 'permission', code: 'privacy_consent.read' },
    groupId: 'privacy',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },
  {
    id: 'privacy-dsr',
    titleKey: 'nav.dataSubjectRequests',
    path: '/app/privacy/dsr',
    matchPatterns: ['/app/privacy/dsr'],
    iconName: 'UserCheck',
    access: { kind: 'permission', code: 'privacy_consent.read' },
    groupId: 'privacy',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 30,
  },
  {
    id: 'privacy-legalhold',
    titleKey: 'nav.legalHold',
    path: '/app/privacy/legal-hold',
    matchPatterns: ['/app/privacy/legal-hold'],
    iconName: 'Lock',
    access: { kind: 'permission', code: 'privacy_consent.read' },
    groupId: 'privacy',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 40,
  },

  // Integration
  {
    id: 'integration-external',
    titleKey: 'nav.externalId',
    path: '/app/integration/external-ids',
    matchPatterns: ['/app/integration/external-ids'],
    iconName: 'Link',
    access: { kind: 'tenant-admin' },
    groupId: 'integration',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'integration-outbox',
    titleKey: 'nav.outbox',
    path: '/app/integration/outbox',
    matchPatterns: ['/app/integration/outbox'],
    iconName: 'Send',
    access: { kind: 'tenant-admin' },
    groupId: 'integration',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },
  {
    id: 'integration-webhooks',
    titleKey: 'nav.webhooks',
    path: '/app/integration/webhooks',
    matchPatterns: ['/app/integration/webhooks'],
    iconName: 'Webhook',
    access: { kind: 'tenant-admin' },
    groupId: 'integration',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 30,
  },
  {
    id: 'integration-import',
    titleKey: 'nav.dataImport',
    path: '/app/integration/import',
    matchPatterns: ['/app/integration/import'],
    iconName: 'Upload',
    access: { kind: 'tenant-admin' },
    groupId: 'integration',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 40,
  },

  // Audit
  {
    id: 'audit-logs',
    titleKey: 'nav.auditLogs',
    path: '/app/audit/logs',
    matchPatterns: ['/app/audit/logs'],
    iconName: 'ClipboardList',
    access: { kind: 'permission', code: 'audit_read' },
    groupId: 'audit',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'audit-access',
    titleKey: 'nav.dataAccess',
    path: '/app/audit/data-access',
    matchPatterns: ['/app/audit/data-access'],
    iconName: 'Eye',
    access: { kind: 'permission', code: 'audit_read' },
    groupId: 'audit',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },

  // Platform
  {
    id: 'platform-users',
    titleKey: 'nav.users',
    path: '/app/platform/users',
    matchPatterns: ['/app/platform/users'],
    iconName: 'User',
    access: { kind: 'permission', code: 'platform_user.manage' },
    groupId: 'platform',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 10,
  },
  {
    id: 'platform-teams',
    titleKey: 'nav.teams',
    path: '/app/platform/teams',
    matchPatterns: ['/app/platform/teams'],
    iconName: 'Network',
    access: { kind: 'permission', code: 'platform_user.manage' },
    groupId: 'platform',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 20,
  },
  {
    id: 'platform-roles',
    titleKey: 'nav.rolesPermissions',
    path: '/app/platform/roles',
    matchPatterns: ['/app/platform/roles'],
    iconName: 'Shield',
    access: { kind: 'permission', code: 'platform_role.read' },
    groupId: 'platform',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 30,
  },
  {
    id: 'platform-settings',
    titleKey: 'nav.tenantSettings',
    path: '/app/platform/settings',
    matchPatterns: ['/app/platform/settings'],
    iconName: 'Settings',
    access: { kind: 'permission', code: 'platform_user.manage' },
    groupId: 'platform',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 40,
  },
  {
    id: 'platform-pipelines',
    titleKey: 'nav.pipelines',
    path: '/app/platform/pipelines',
    matchPatterns: ['/app/platform/pipelines'],
    iconName: 'Workflow',
    access: { kind: 'permission', code: 'platform_user.manage' },
    groupId: 'platform',
    showInSidebar: true,
    showInCommandPalette: true,
    order: 50,
  },
];
