import { NavigationGroup } from '@/types/navigation';

export const NAVIGATION_GROUPS: NavigationGroup[] = [
  {
    id: 'crm',
    titleVi: 'Quản lý Khách hàng (CRM)',
    titleEn: 'Customer Relationship Management',
    items: [
      {
        id: 'crm-accounts',
        moduleGroup: 'crm',
        titleVi: 'Khách hàng',
        titleEn: 'Accounts',
        path: '/app/crm/accounts',
        iconName: 'Building2',
        requiredPermission: 'crm_account.read',
      },
      {
        id: 'crm-contacts',
        moduleGroup: 'crm',
        titleVi: 'Người liên hệ',
        titleEn: 'Contacts',
        path: '/app/crm/contacts',
        iconName: 'Users',
        requiredPermission: 'crm_contact.read',
      },
      {
        id: 'crm-leads',
        moduleGroup: 'crm',
        titleVi: 'Khách hàng tiềm năng',
        titleEn: 'Leads',
        path: '/app/crm/leads',
        iconName: 'UserPlus',
        requiredPermission: 'crm_lead.read',
      },
      {
        id: 'crm-opportunities',
        moduleGroup: 'crm',
        titleVi: 'Cơ hội kinh doanh',
        titleEn: 'Opportunities',
        path: '/app/crm/opportunities',
        iconName: 'TrendingUp',
        requiredPermission: 'crm_opportunity.read',
      },
      {
        id: 'crm-activities',
        moduleGroup: 'crm',
        titleVi: 'Hoạt động',
        titleEn: 'Activities',
        path: '/app/crm/activities',
        iconName: 'Calendar',
        requiresAnyCrmReadPermission: true,
      },
    ],
  },
  {
    id: 'sales',
    titleVi: 'Bán hàng & Đơn hàng',
    titleEn: 'Sales & Orders',
    items: [
      {
        id: 'sales-quotes',
        moduleGroup: 'sales',
        titleVi: 'Báo giá',
        titleEn: 'Quotes',
        path: '/app/sales/quotes',
        iconName: 'FileText',
        requiredPermission: 'sales_quote.read',
      },
      {
        id: 'sales-orders',
        moduleGroup: 'sales',
        titleVi: 'Đơn hàng',
        titleEn: 'Orders',
        path: '/app/sales/orders',
        iconName: 'ShoppingCart',
        requiredPermission: 'sales_order.read',
      },
      {
        id: 'sales-contracts',
        moduleGroup: 'sales',
        titleVi: 'Hợp đồng',
        titleEn: 'Contracts',
        path: '/app/sales/contracts',
        iconName: 'FileSignature',
        requiredPermission: 'sales_order.read',
      },
    ],
  },
  {
    id: 'catalog',
    titleVi: 'Danh mục Sản phẩm',
    titleEn: 'Product Catalog',
    items: [
      {
        id: 'catalog-categories',
        moduleGroup: 'catalog',
        titleVi: 'Danh mục sản phẩm',
        titleEn: 'Categories',
        path: '/app/catalog/categories',
        iconName: 'FolderTree',
        requiresTenantAdmin: true,
      },
      {
        id: 'catalog-products',
        moduleGroup: 'catalog',
        titleVi: 'Sản phẩm',
        titleEn: 'Products',
        path: '/app/catalog/products',
        iconName: 'Package',
        requiresTenantAdmin: true,
      },
      {
        id: 'catalog-pricebooks',
        moduleGroup: 'catalog',
        titleVi: 'Bảng giá',
        titleEn: 'Price Books',
        path: '/app/catalog/price-books',
        iconName: 'Tag',
        requiresTenantAdmin: true,
      },
    ],
  },
  {
    id: 'service',
    titleVi: 'Dịch vụ & Hỗ trợ',
    titleEn: 'Customer Service',
    items: [
      {
        id: 'service-tickets',
        moduleGroup: 'service',
        titleVi: 'Yêu cầu hỗ trợ',
        titleEn: 'Service Tickets',
        path: '/app/service/tickets',
        iconName: 'LifeBuoy',
        requiredPermission: 'service_ticket.read',
      },
    ],
  },
  {
    id: 'marketing',
    titleVi: 'Marketing',
    titleEn: 'Marketing',
    items: [
      {
        id: 'marketing-campaigns',
        moduleGroup: 'marketing',
        titleVi: 'Chiến dịch',
        titleEn: 'Campaigns',
        path: '/app/marketing/campaigns',
        iconName: 'Megaphone',
        requiresTenantAdmin: true,
      },
    ],
  },
  {
    id: 'privacy',
    titleVi: 'Bảo mật & Quyền riêng tư',
    titleEn: 'Privacy & Compliance',
    items: [
      {
        id: 'privacy-consent',
        moduleGroup: 'privacy',
        titleVi: 'Đồng ý riêng tư',
        titleEn: 'Privacy Consents',
        path: '/app/privacy/consent',
        iconName: 'ShieldCheck',
        requiredPermission: 'privacy_consent.read',
      },
      {
        id: 'privacy-retention',
        moduleGroup: 'privacy',
        titleVi: 'Chính sách lưu giữ',
        titleEn: 'Retention Policies',
        path: '/app/privacy/retention',
        iconName: 'Archive',
        requiredPermission: 'privacy_consent.read',
      },
      {
        id: 'privacy-dsr',
        moduleGroup: 'privacy',
        titleVi: 'Yêu cầu chủ thể dữ liệu',
        titleEn: 'Data Subject Requests',
        path: '/app/privacy/dsr',
        iconName: 'UserCheck',
        requiredPermission: 'privacy_consent.read',
      },
      {
        id: 'privacy-legalhold',
        moduleGroup: 'privacy',
        titleVi: 'Legal Hold',
        titleEn: 'Legal Hold',
        path: '/app/privacy/legal-hold',
        iconName: 'Lock',
        requiredPermission: 'privacy_consent.read',
      },
    ],
  },
  {
    id: 'integration',
    titleVi: 'Tích hợp hệ thống',
    titleEn: 'System Integrations',
    items: [
      {
        id: 'integration-external',
        moduleGroup: 'integration',
        titleVi: 'External ID',
        titleEn: 'External IDs',
        path: '/app/integration/external-ids',
        iconName: 'Link',
        requiresTenantAdmin: true,
      },
      {
        id: 'integration-outbox',
        moduleGroup: 'integration',
        titleVi: 'Outbox Event',
        titleEn: 'Outbox Events',
        path: '/app/integration/outbox',
        iconName: 'Send',
        requiresTenantAdmin: true,
      },
      {
        id: 'integration-webhooks',
        moduleGroup: 'integration',
        titleVi: 'Webhook',
        titleEn: 'Webhooks',
        path: '/app/integration/webhooks',
        iconName: 'Webhook',
        requiresTenantAdmin: true,
      },
      {
        id: 'integration-import',
        moduleGroup: 'integration',
        titleVi: 'Nhập dữ liệu',
        titleEn: 'Data Import',
        path: '/app/integration/import',
        iconName: 'Upload',
        requiresTenantAdmin: true,
      },
    ],
  },
  {
    id: 'audit',
    titleVi: 'Kiểm toán & Truy vết',
    titleEn: 'Audit & Compliance',
    items: [
      {
        id: 'audit-logs',
        moduleGroup: 'audit',
        titleVi: 'Nhật ký kiểm toán',
        titleEn: 'Audit Logs',
        path: '/app/audit/logs',
        iconName: 'ClipboardList',
        requiredPermission: 'audit_read',
      },
      {
        id: 'audit-access',
        moduleGroup: 'audit',
        titleVi: 'Truy cập dữ liệu',
        titleEn: 'Data Access',
        path: '/app/audit/data-access',
        iconName: 'Eye',
        requiredPermission: 'audit_read',
      },
    ],
  },
  {
    id: 'platform',
    titleVi: 'Quản trị Nền tảng',
    titleEn: 'Platform Administration',
    items: [
      {
        id: 'platform-users',
        moduleGroup: 'platform',
        titleVi: 'Người dùng',
        titleEn: 'Users',
        path: '/app/platform/users',
        iconName: 'User',
        requiredPermission: 'platform_user.manage',
      },
      {
        id: 'platform-teams',
        moduleGroup: 'platform',
        titleVi: 'Nhóm & Phòng ban',
        titleEn: 'Teams & Departments',
        path: '/app/platform/teams',
        iconName: 'Network',
        requiredPermission: 'platform_user.manage',
      },
      {
        id: 'platform-roles',
        moduleGroup: 'platform',
        titleVi: 'Vai trò & Quyền',
        titleEn: 'Roles & Permissions',
        path: '/app/platform/roles',
        iconName: 'Shield',
        requiredPermission: 'platform_user.manage',
      },
      {
        id: 'platform-settings',
        moduleGroup: 'platform',
        titleVi: 'Cài đặt Tổ chức',
        titleEn: 'Tenant Settings',
        path: '/app/platform/settings',
        iconName: 'Settings',
        requiredPermission: 'platform_user.manage',
      },
    ],
  },
];
