package com.crm.privacy.domain;

public enum PrivacyErrorCode {

	CONSENT_NOT_FOUND("CONSENT_NOT_FOUND"),
	INVALID_CONSENT_TARGET("INVALID_CONSENT_TARGET"),
	CONSENT_ALREADY_WITHDRAWN("CONSENT_ALREADY_WITHDRAWN"),
	RETENTION_POLICY_NOT_FOUND("RETENTION_POLICY_NOT_FOUND"),
	RETENTION_POLICY_ALREADY_EXISTS("RETENTION_POLICY_ALREADY_EXISTS"),
	DSR_NOT_FOUND("DSR_NOT_FOUND"),
	DSR_NUMBER_ALREADY_EXISTS("DSR_NUMBER_ALREADY_EXISTS"),
	INVALID_DSR_STATUS_TRANSITION("INVALID_DSR_STATUS_TRANSITION"),
	LEGAL_HOLD_NOT_FOUND("LEGAL_HOLD_NOT_FOUND"),
	LEGAL_HOLD_CODE_ALREADY_EXISTS("LEGAL_HOLD_CODE_ALREADY_EXISTS"),
	LEGAL_HOLD_ALREADY_RELEASED("LEGAL_HOLD_ALREADY_RELEASED"),
	PRIVACY_VERSION_CONFLICT("PRIVACY_VERSION_CONFLICT");

	private final String code;

	PrivacyErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return code;
	}

}
