package com.crm.platform.team.domain;

public enum TeamErrorCode {

	TEAM_NOT_FOUND("TEAM_NOT_FOUND"),
	TEAM_NAME_ALREADY_EXISTS("TEAM_NAME_ALREADY_EXISTS"),
	TEAM_CIRCULAR_PARENT_REFERENCE("TEAM_CIRCULAR_PARENT_REFERENCE"),
	TEAM_MEMBER_NOT_FOUND("TEAM_MEMBER_NOT_FOUND"),
	TEAM_MEMBER_ALREADY_EXISTS("TEAM_MEMBER_ALREADY_EXISTS"),
	DATA_SCOPE_NOT_FOUND("DATA_SCOPE_NOT_FOUND"),
	INVALID_DATA_SCOPE_CONFIGURATION("INVALID_DATA_SCOPE_CONFIGURATION"),
	ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
	USER_NOT_FOUND("USER_NOT_FOUND"),
	TEAM_VERSION_CONFLICT("TEAM_VERSION_CONFLICT");

	private final String code;

	TeamErrorCode(String code) {
		this.code = code;
	}

	public String code() {
		return code;
	}

}
